wip

diff --git a/.github/actions/gather/action.yml b/.github/actions/gather/action.yml
--- a/.github/actions/gather/action.yml
+++ b/.github/actions/gather/action.yml
@@ -20,14 +20,14 @@ runs:
       run: |
         set -euxo pipefail
 
-        releases_json="$(gh release list --limit 2000 --json tagName)"
+        gh release list --limit 2000 --json tagName > releases.json
 
         for sysext in $(echo ${SYSEXTS} | tr ';' ' '); do
           rm -f ./SHA256SUMS* ./*.conf
 
           releases=(
             $(
-              echo "${releases_json}" \
+              cat releases.json \
                 | jq --arg SYSEXT "${sysext}" --raw-output '
                   map(
                     select(
@@ -44,7 +44,8 @@ runs:
           echo "Looking at releases: ${releases[@]}"
           for rel in ${releases[@]}; do
             echo "Fetching SHA256SUMS for release: ${rel}"
-            curl --location --fail --output "SHA256SUMS.${rel}" "${RELEASEURL}/${rel}/SHA256SUMS"
+            curl --location --fail --output "SHA256SUMS.${rel}" "${RELEASEURL}/${rel}/SHA256SUMS" \
+              || { echo "Failed to fetch SHA256SUMS for ${rel}"; touch "SHA256SUMS.${rel}" }
           done
           ls ./SHA256SUMS.* | sort -h | xargs cat > SHA256SUMS
           new="$(cat SHA256SUMS | sha256sum)"
@@ -83,8 +84,11 @@ runs:
           fi
         done
 
+        rm -f ./SHA256SUMS* ./*.conf
+
         for sysext in $(echo ${SYSEXTS} | tr ';' ' '); do
-            curl --location --fail --output "SHA256SUMS.${sysext}" "${RELEASEURL}/${sysext}/SHA256SUMS"
+            curl --location --fail --output "SHA256SUMS.${sysext}" "${RELEASEURL}/${sysext}/SHA256SUMS" \
+              || { echo "Failed to fetch SHA256SUMS for ${sysext}"; touch "SHA256SUMS.${sysext}" }
         done
         ls ./SHA256SUMS.* | sort -h | xargs cat > SHA256SUMS
 
